/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Ch19: THREE.SkinnedMesh
    mixamorig1Hips: THREE.Bone
    mixamorig1Spine: THREE.Bone
    mixamorig1Neck: THREE.Bone
    mixamorig1LeftShoulder: THREE.Bone
    mixamorig1LeftArm: THREE.Bone
    mixamorig1LeftForeArm: THREE.Bone
    mixamorig1LeftHand: THREE.Bone
    mixamorig1LeftHandThumb1: THREE.Bone
    mixamorig1LeftHandThumb2: THREE.Bone
    mixamorig1LeftHandThumb3: THREE.Bone
    mixamorig1LeftHandIndex1: THREE.Bone
    mixamorig1LeftHandIndex2: THREE.Bone
    mixamorig1LeftHandIndex3: THREE.Bone
    mixamorig1LeftHandMiddle1: THREE.Bone
    mixamorig1LeftHandMiddle2: THREE.Bone
    mixamorig1LeftHandMiddle3: THREE.Bone
    mixamorig1LeftHandRing1: THREE.Bone
    mixamorig1LeftHandRing2: THREE.Bone
    mixamorig1LeftHandRing3: THREE.Bone
    mixamorig1RightShoulder: THREE.Bone
    mixamorig1RightArm: THREE.Bone
    mixamorig1RightForeArm: THREE.Bone
    mixamorig1RightHand: THREE.Bone
    mixamorig1RightHandThumb1: THREE.Bone
    mixamorig1RightHandThumb2: THREE.Bone
    mixamorig1RightHandThumb3: THREE.Bone
    mixamorig1RightHandIndex1: THREE.Bone
    mixamorig1RightHandIndex2: THREE.Bone
    mixamorig1RightHandIndex3: THREE.Bone
    mixamorig1RightHandMiddle1: THREE.Bone
    mixamorig1RightHandMiddle2: THREE.Bone
    mixamorig1RightHandMiddle3: THREE.Bone
    mixamorig1RightHandRing1: THREE.Bone
    mixamorig1RightHandRing2: THREE.Bone
    mixamorig1RightHandRing3: THREE.Bone
    mixamorig1LeftUpLeg: THREE.Bone
    mixamorig1LeftLeg: THREE.Bone
    mixamorig1LeftFoot: THREE.Bone
    mixamorig1LeftToeBase: THREE.Bone
    mixamorig1RightUpLeg: THREE.Bone
    mixamorig1RightLeg: THREE.Bone
    mixamorig1RightFoot: THREE.Bone
    mixamorig1RightToeBase: THREE.Bone
  }
  materials: {
    Ch19_Body: THREE.MeshStandardMaterial
  }
}

type ActionName =
  | 'animation_0'
  | 'animation_1'
  | 'animation_2'
  | 'animation_3'
  | 'animation_4'
  | 'animation_5'
  | 'animation_6'
  | 'animation_7'
  | 'animation_8'
  | 'animation_9'
  | 'animation_10'
  | 'animation_11'
  | 'animation_12'
  | 'animation_13'
  | 'animation_14'
  | 'animation_15'
  | 'animation_16'
  | 'animation_17'
  | 'animation_18'
  | 'animation_19'
  | 'animation_20'
  | 'animation_21'
  | 'animation_22'
  | 'animation_23'
  | 'animation_24'
  | 'animation_25'
  | 'animation_26'
  | 'animation_27'
  | 'animation_28'
  | 'animation_29'
  | 'animation_30'
  | 'animation_31'
  | 'animation_32'
  | 'animation_33'
  | 'animation_34'
  | 'animation_35'
  | 'animation_36'
  | 'animation_37'
  | 'animation_38'
  | 'animation_39'
  | 'animation_40'
  | 'animation_41'
  | 'animation_42'
  | 'animation_43'
  | 'animation_44'
  | 'animation_45'
  | 'animation_46'
  | 'animation_47'
  | 'animation_48'
  | 'animation_49'
  | 'animation_50'
  | 'animation_51'
  | 'animation_52'
  | 'animation_53'
  | 'animation_54'
  | 'animation_55'
  | 'animation_56'
  | 'animation_57'
  | 'animation_58'
  | 'animation_59'
  | 'animation_60'
  | 'animation_61'
  | 'animation_62'
  | 'animation_63'
  | 'animation_64'
  | 'animation_65'
  | 'animation_66'
  | 'animation_67'
  | 'animation_68'

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('./assets/walking.gltf') as any
  const { actions } = useAnimations<any>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.mixamorig1Hips} />
      <skinnedMesh geometry={nodes.Ch19.geometry} material={materials.Ch19_Body} skeleton={nodes.Ch19.skeleton} />
    </group>
  )
}

useGLTF.preload('/walking.gltf')
